// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315143322_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("DAL.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "Lớp học cung cấp kiến thức cơ bản về lập trình C# bao gồm biến, kiểu dữ liệu, vòng lặp, câu lệnh điều kiện và các khái niệm lập trình hướng đối tượng.",
                            EndDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 30,
                            Name = "C# cơ bản - Lớp sáng",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Description = "Khóa học giúp học viên nâng cao kỹ năng lập trình với LINQ, async/await, dependency injection và các design pattern thường dùng.",
                            EndDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 25,
                            Name = "C# nâng cao - Lớp tối",
                            StartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Description = "Học xây dựng ứng dụng web hiện đại với ASP.NET Core, MVC, Razor Pages và Web API.",
                            EndDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 35,
                            Name = "Lập trình Web ASP.NET Core",
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Description = "Học thiết kế cơ sở dữ liệu, viết truy vấn SQL, sử dụng join, stored procedure và tối ưu truy vấn.",
                            EndDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 40,
                            Name = "Quản trị SQL Server",
                            StartDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Description = "Giới thiệu nguyên tắc Clean Architecture và cách áp dụng trong các dự án .NET thực tế.",
                            EndDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 20,
                            Name = "Clean Architecture",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 1,
                            Description = "Lớp học C# cơ bản đã hoàn thành.",
                            EndDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 30,
                            Name = "C# cơ bản - Lớp 2024",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            Description = "Lớp ASP.NET Core đang diễn ra.",
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 30,
                            Name = "ASP.NET Core - Lớp hiện tại",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 5,
                            Description = "Lớp Clean Architecture sẽ mở trong tương lai.",
                            EndDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 20,
                            Name = "Clean Architecture - Lớp tương lai",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            Description = "Lớp học C# cơ bản dành cho ca chiều.",
                            EndDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 30,
                            Name = "C# cơ bản - Lớp chiều",
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 1,
                            Description = "Lớp học C# cơ bản ca tối cho người đi làm.",
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 30,
                            Name = "C# cơ bản - Lớp tối",
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 2,
                            Description = "Chuyên đề nâng cao về LINQ, async await và performance.",
                            EndDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 25,
                            Name = "C# nâng cao - Lớp chuyên đề",
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 3,
                            Description = "Xây dựng RESTful API với ASP.NET Core.",
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 30,
                            Name = "ASP.NET Core API",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 1,
                            Description = "Lớp học cuối tuần cho người bận rộn.",
                            EndDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 35,
                            Name = "C# cơ bản - Lớp cuối tuần",
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.ClassImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ClassImg")
                        .HasColumnType("image")
                        .HasColumnName("ClassImg");

                    b.HasKey("Id");

                    b.ToTable("ClassImages");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Học lập trình C# từ cơ bản",
                            Duration = 30,
                            Name = "Lập trình C# cơ bản",
                            Price = 3000000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các kỹ thuật C# nâng cao",
                            Duration = 45,
                            Name = "Lập trình C# nâng cao",
                            Price = 5000000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Xây dựng Web API",
                            Duration = 40,
                            Name = "Phát triển Web ASP.NET Core",
                            Price = 4500000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Quản lý và truy vấn dữ liệu",
                            Duration = 25,
                            Name = "Cơ sở dữ liệu SQL Server",
                            Price = 2500000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Thiết kế kiến trúc phần mềm",
                            Duration = 20,
                            Name = "Clean Architecture trong .NET",
                            Price = 4000000m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("DAL.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            EnrollDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            EnrollDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 3,
                            EnrollDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 4,
                            EnrollDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 5,
                            EnrollDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 1,
                            EnrollDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 1,
                            EnrollDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 1,
                            EnrollDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 2,
                            EnrollDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 2,
                            EnrollDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 3,
                            EnrollDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 3,
                            EnrollDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 4,
                            EnrollDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 4,
                            EnrollDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 5,
                            EnrollDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 9,
                            EnrollDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 9,
                            EnrollDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 9,
                            EnrollDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 9,
                            EnrollDate = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 10,
                            EnrollDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 10,
                            EnrollDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 10,
                            EnrollDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 10,
                            EnrollDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 11,
                            EnrollDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 11,
                            EnrollDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 11,
                            EnrollDate = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 11,
                            EnrollDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 12,
                            EnrollDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 12,
                            EnrollDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 12,
                            EnrollDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 13,
                            EnrollDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 13,
                            EnrollDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 13,
                            EnrollDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 13,
                            EnrollDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 13,
                            EnrollDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StudentId = 8
                        });
                });

            modelBuilder.Entity("DAL.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = 2
                        });
                });

            modelBuilder.Entity("DAL.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A101",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            Room = "B202",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 3,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            Room = "C303",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 4,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Room = "D404",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 5,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            Room = "E505",
                            StartTime = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 1,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A101",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 2,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            Room = "B202",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 3,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            Room = "C303",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 7,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Room = "D404",
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 7,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Room = "D404",
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 6,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A102",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 6,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Room = "A102",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 8,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            Room = "E101",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 8,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            Room = "E101",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 9,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Room = "A201",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 9,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Room = "A201",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 10,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            Room = "B301",
                            StartTime = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 10,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            Room = "B301",
                            StartTime = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 11,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            Room = "C401",
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 12,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Room = "D501",
                            StartTime = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 12,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Room = "D501",
                            StartTime = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 13,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Room = "E601",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 13,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            Room = "E601",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("DAL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Minh Đức",
                            Gender = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "TP Hồ Chí Minh",
                            DateOfBirth = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Ngọc Anh",
                            Gender = 1,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Đà Nẵng",
                            DateOfBirth = new DateTime(1999, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Hoàng Nam",
                            Gender = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Huế",
                            DateOfBirth = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Thu Trang",
                            Gender = 1,
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cần Thơ",
                            DateOfBirth = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Đỗ Văn Phúc",
                            Gender = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Hà Nội",
                            DateOfBirth = new DateTime(2001, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn Thiện",
                            Gender = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Hải Phòng",
                            DateOfBirth = new DateTime(2000, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thị Bé",
                            Gender = 1,
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "Đà Nẵng",
                            DateOfBirth = new DateTime(1998, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Văn Cảnh",
                            Gender = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            Address = "Cần Thơ",
                            DateOfBirth = new DateTime(2002, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Thị Dung",
                            Gender = 1,
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            Address = "Huế",
                            DateOfBirth = new DateTime(1999, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hoàng Văn Ôn",
                            Gender = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 11,
                            Address = "Quảng Ninh",
                            DateOfBirth = new DateTime(2003, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Đặng Thị Huệ",
                            Gender = 1,
                            UserId = 0
                        },
                        new
                        {
                            Id = 12,
                            Address = "Bình Dương",
                            DateOfBirth = new DateTime(2001, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bùi Văn Giang",
                            Gender = 0,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("DAL.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teacher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "Thạc sĩ Công nghệ thông tin",
                            Experience = 5,
                            FullName = "Nguyễn Văn An",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Degree = "Tiến sĩ Khoa học máy tính",
                            Experience = 8,
                            FullName = "Trần Thị Bích",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Degree = "Cử nhân Công nghệ thông tin",
                            Experience = 3,
                            FullName = "Lê Văn Cường",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            Degree = "Thạc sĩ Hệ thống thông tin",
                            Experience = 6,
                            FullName = "Phạm Thị Dung",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            Degree = "Tiến sĩ Công nghệ phần mềm",
                            Experience = 10,
                            FullName = "Hoàng Văn Hiếu",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("DAL.Models.TeacherReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TeacherReview");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
